
const express = require("express");

const router = express.Router();

const validatePatient = require("../middlewares/patientValidation");
const authenticateToken = require("../middlewares/authMiddleware");
const authorizeRoles = require("../middlewares/roleMiddleware");

const {
    createPatient,
    getAllPatients,
    getPatientById,
    updatePatient,
    deletePatient,
    searchPatients
} = require("../controllers/patientController");


// ============================================================
// GET ALL PATIENTS
// ============================================================

/**
 * @swagger
 * /patients:
 *   get:
 *     summary: Get all patients
 *     description: Retrieve all registered patients.
 *     tags:
 *       - Patients
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: Patients retrieved successfully.
 *       401:
 *         description: Unauthorized.
 *       403:
 *         description: Forbidden.
 */
router.get(
    "/",
    authenticateToken,
    authorizeRoles(
        "admin",
        "doctor",
        "receptionist",
        "staff"
    ),
    getAllPatients
);


// ============================================================
// SEARCH PATIENTS
// ============================================================

/**
 * @swagger
 * /patients/search:
 *   get:
 *     summary: Search patients
 *     description: Search patients by name, email, phone, or patient number.
 *     tags:
 *       - Patients
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: q
 *         required: true
 *         schema:
 *           type: string
 *         description: Search keyword
 *         example: GHS-2026-000001
 *     responses:
 *       200:
 *         description: Patients retrieved successfully.
 *       401:
 *         description: Unauthorized.
 */
router.get(
    "/search",
    authenticateToken,
    authorizeRoles(
        "admin",
        "doctor",
        "receptionist",
        "staff"
    ),
    searchPatients
);


// ============================================================
// GET PATIENT BY ID
// ============================================================

/**
 * @swagger
 * /patients/{id}:
 *   get:
 *     summary: Get patient by ID
 *     description: Retrieve a complete patient profile.
 *     tags:
 *       - Patients
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *         description: Internal patient ID
 *     responses:
 *       200:
 *         description: Patient retrieved successfully.
 *       404:
 *         description: Patient not found.
 *       401:
 *         description: Unauthorized.
 *       403:
 *         description: Forbidden.
 */
router.get(
    "/:id",
    authenticateToken,
    authorizeRoles(
        "admin",
        "doctor",
        "receptionist",
        "staff"
    ),
    getPatientById
);


// ============================================================
// REGISTER NEW PATIENT
// ============================================================

/**
 * @swagger
 * /patients:
 *   post:
 *     summary: Register a new patient
 *     description: Register a patient with personal, demographic, medical, and emergency contact information. Patient number and system timestamps are generated by the backend.
 *     tags:
 *       - Patients
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - first_name
 *               - last_name
 *               - gender
 *               - email
 *               - phone
 *               - address
 *               - date_of_birth
 *             properties:
 *
 *               first_name:
 *                 type: string
 *                 example: Aisha
 *
 *               last_name:
 *                 type: string
 *                 example: Bello
 *
 *               gender:
 *                 type: string
 *                 enum:
 *                   - Male
 *                   - Female
 *                   - Other
 *                 example: Female
 *
 *               email:
 *                 type: string
 *                 format: email
 *                 example: aisha.bello@gmail.com
 *
 *               phone:
 *                 type: string
 *                 example: "+2348012345678"
 *
 *               address:
 *                 type: string
 *                 example: Wuse 2, Abuja, Nigeria
 *
 *               date_of_birth:
 *                 type: string
 *                 format: date
 *                 example: "1998-05-12"
 *
 *               blood_group:
 *                 type: string
 *                 enum:
 *                   - A+
 *                   - A-
 *                   - B+
 *                   - B-
 *                   - AB+
 *                   - AB-
 *                   - O+
 *                   - O-
 *                 example: O+
 *
 *               genotype:
 *                 type: string
 *                 enum:
 *                   - AA
 *                   - AS
 *                   - AC
 *                   - SS
 *                   - SC
 *                 example: AA
 *
 *               marital_status:
 *                 type: string
 *                 enum:
 *                   - Single
 *                   - Married
 *                   - Divorced
 *                   - Widowed
 *                 example: Single
 *
 *               occupation:
 *                 type: string
 *                 example: Teacher
 *
 *               emergency_contact_name:
 *                 type: string
 *                 example: Ibrahim Bello
 *
 *               emergency_contact_phone:
 *                 type: string
 *                 example: "+2348098765432"
 *
 *               emergency_contact_relationship:
 *                 type: string
 *                 example: Brother
 *
 *               allergies:
 *                 type: string
 *                 example: Penicillin
 *
 *               medical_history:
 *                 type: string
 *                 example: Previous malaria treatment
 *
 *     responses:
 *       201:
 *         description: Patient created successfully.
 *       400:
 *         description: Validation error.
 *       401:
 *         description: Unauthorized.
 *       403:
 *         description: Forbidden.
 */
router.post(
    "/",
    authenticateToken,
    authorizeRoles(
        "admin",
        "receptionist",
        "staff"
    ),
    validatePatient,
    createPatient
);


// ============================================================
// UPDATE PATIENT
// ============================================================

/**
 * @swagger
 * /patients/{id}:
 *   put:
 *     summary: Update patient
 *     description: Update an existing patient's demographic, contact, medical, or emergency information.
 *     tags:
 *       - Patients
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *         description: Internal patient ID
 *
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *
 *               first_name:
 *                 type: string
 *
 *               last_name:
 *                 type: string
 *
 *               gender:
 *                 type: string
 *                 enum:
 *                   - Male
 *                   - Female
 *                   - Other
 *
 *               email:
 *                 type: string
 *                 format: email
 *
 *               phone:
 *                 type: string
 *
 *               address:
 *                 type: string
 *
 *               date_of_birth:
 *                 type: string
 *                 format: date
 *
 *               blood_group:
 *                 type: string
 *                 enum:
 *                   - A+
 *                   - A-
 *                   - B+
 *                   - B-
 *                   - AB+
 *                   - AB-
 *                   - O+
 *                   - O-
 *
 *               genotype:
 *                 type: string
 *                 enum:
 *                   - AA
 *                   - AS
 *                   - AC
 *                   - SS
 *                   - SC
 *
 *               marital_status:
 *                 type: string
 *                 enum:
 *                   - Single
 *                   - Married
 *                   - Divorced
 *                   - Widowed
 *
 *               occupation:
 *                 type: string
 *
 *               emergency_contact_name:
 *                 type: string
 *
 *               emergency_contact_phone:
 *                 type: string
 *
 *               emergency_contact_relationship:
 *                 type: string
 *
 *               allergies:
 *                 type: string
 *
 *               medical_history:
 *                 type: string
 *
 *     responses:
 *       200:
 *         description: Patient updated successfully.
 *       404:
 *         description: Patient not found.
 *       400:
 *         description: Validation error.
 *       401:
 *         description: Unauthorized.
 *       403:
 *         description: Forbidden.
 */
router.put(
    "/:id",
    authenticateToken,
    authorizeRoles(
        "admin",
        "doctor",
        "receptionist"
    ),
    validatePatient,
    updatePatient
);


// ============================================================
// DELETE PATIENT
// ============================================================

/**
 * @swagger
 * /patients/{id}:
 *   delete:
 *     summary: Delete a patient
 *     description: Permanently delete a patient record. Restricted to administrators.
 *     tags:
 *       - Patients
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *         description: Internal patient ID
 *     responses:
 *       200:
 *         description: Patient deleted successfully.
 *       404:
 *         description: Patient not found.
 *       401:
 *         description: Unauthorized.
 *       403:
 *         description: Forbidden.
 */
router.delete(
    "/:id",
    authenticateToken,
    authorizeRoles("admin"),
    deletePatient
);


module.exports = router;

